project_id = "ztacnsjedynqidqrknui"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cross-device-sync]
verify_jwt = false

[functions.generate-interview-answer]
verify_jwt = false

[functions.process-session-assets]
verify_jwt = false

[functions.process-transcription]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.send-upload-link]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.test-webhook-config]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false