// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztacnsjedynqidqrknui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0YWNuc2plZHlucWlkcXJrbnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjc4NzIsImV4cCI6MjA3Mjg0Mzg3Mn0.MALlhb1j8PcMvhL5CAY-1j0M_0dq46Llq7TkOt-sp_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});